language: php

php: 
  #- 5.3
  - 5.4

before_script: 
  - git submodule update --init
  - export BUILD_HOME=`pwd`
  - export PYRUS=`which pyrus`
  - export PHPUNIT_HOME=`pwd`/../phpunit35/

  - mkdir $PHPUNIT_HOME
  - mkdir ${PHPUNIT_HOME}/bin
  - cd $PHPUNIT_HOME
  - $PYRUS $PHPUNIT_HOME set bin_dir ./bin
  - wget http://components.ez.no/get/Base-1.8.tgz
  - wget http://components.ez.no/get/ConsoleTools-1.6.1.tgz

  - $PYRUS $PHPUNIT_HOME channel-discover pear.phpunit.de
  - $PYRUS $PHPUNIT_HOME channel-discover components.ez.no
  - $PYRUS $PHPUNIT_HOME channel-discover pear.symfony-project.com
  - $PYRUS $PHPUNIT_HOME install Base-1.8.tgz 
  - $PYRUS $PHPUNIT_HOME install ConsoleTools-1.6.1.tgz 

  - $PYRUS $PHPUNIT_HOME install pear.phpunit.de/File_Iterator-1.2.6
  - $PYRUS $PHPUNIT_HOME install pear.phpunit.de/PHPUnit_MockObject-1.0.9
  - $PYRUS $PHPUNIT_HOME install pear.phpunit.de/PHPUnit_Selenium-1.0.3
  - $PYRUS $PHPUNIT_HOME install pear.phpunit.de/PHP_TokenStream-1.0.1
  - $PYRUS $PHPUNIT_HOME install pear.phpunit.de/PHP_Timer
  - $PYRUS $PHPUNIT_HOME install pear.phpunit.de/PHP_CodeCoverage-1.0.5
  - $PYRUS $PHPUNIT_HOME install pear.phpunit.de/DbUnit-1.0.3
  - $PYRUS $PHPUNIT_HOME install --optionaldeps pear.phpunit.de/PHPUnit-3.5.15

  - awk '{if(NR==1){print $0,"-d include_path='$PHPUNIT_HOME'php"}else{print }}' ${PHPUNIT_HOME}bin/phpunit > ${PHPUNIT_HOME}bin/phpunit35
  #- cat ${PHPUNIT_HOME}bin/phpunit35
  - chmod 755 ${PHPUNIT_HOME}bin/phpunit35
  - export PHPUNIT=${PHPUNIT_HOME}bin/phpunit35
  - $PHPUNIT --version
  - cd $BUILD_HOME/tests
  
script: $PHPUNIT Zend/DebugTest.php

